name: Deploy

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Split servers variable
        id: split_servers
        run: |
          echo "${{ env.SERVERS }}" | tr ',' '\n' >> servers.txt

      - name: Read servers file
        id: read_servers
        run: |
          echo "SERVERS=$(cat servers.txt)" >> $GITHUB_ENV

      - name: Send deploy requests
        run: |
          IFS=$'\n' read -d '' -ra servers <<< "${SERVERS}"
          for server in "${servers[@]}"; do
            curl -X GET \
              -H "Host: restorecord.com" \
              "http://$server/api/admin/deploy?token=${{ env.DEPLOY_TOKEN }}"
          done
